name: Test

on:
  pull_request:
    branches: [main, dev]
  push:
    branches: [main, dev]

jobs:
  build-lint-format-and-test:
    runs-on: ubuntu-latest

    steps:
      ## Checkout Repository
      - name: ğŸ›ï¸ Checkout
        uses: actions/checkout@v4

      ## Install UV Package Manager
      - name: ğŸ“¦ Install uv
        uses: astral-sh/setup-uv@v4

      ## Setup Python Environment
      - name: ğŸ Set up Python
        uses: actions/setup-python@v5
        with:
          python-version-file: ".python-version"

      ## Install Dependencies
      - name: ğŸ¦¾ Install the project
        run: |
          uv sync --all-extras --dev
          uv pip install -e .

      ## Code Quality Checks
      - name: ğŸ’… Lint and Format Check
        run: |
          task check_code_quality

      ## Run Unit Tests
      - name: ğŸ§ª Unit Tests
        run: |
          export PYTHONPATH=src:$PYTHONPATH
          uv run pytest tests/

      ## Test Coverage Report
      - name: ğŸ“Š Test Coverage
        run: |
          uv run pytest --cov=src/cloudops --cov-report=xml tests/

      ## Upload Coverage Report
      - name: ğŸ“ˆ Upload Coverage to Codecov
        uses: codecov/codecov-action@v4
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          file: ./coverage.xml
