name: Test

on:
  pull_request:
    branches: [main, dev]
  push:
    branches: [main, dev]

jobs:
  build-lint-format-and-test:
    runs-on: ubuntu-latest

    steps:
      ## Checkout Repository
      - name: ðŸ›Žï¸ Checkout
        uses: actions/checkout@v4

      ## Install UV Package Manager
      - name: ðŸ“¦ Install uv
        uses: astral-sh/setup-uv@v4

      ## Setup Python Environment
      - name: ðŸ Set up Python
        uses: actions/setup-python@v5
        with:
          python-version-file: ".python-version"

      ## Install Dependencies
      - name: ðŸ¦¾ Install the project
        run: |
          uv sync --all-extras --dev
          uv pip install -e .

      ## --- Install 'task' CLI ---
      - name: Install Taskfile CLI
        run: |
          sudo sh -c "$(curl --location https://taskfile.dev/install.sh)" -- -d -b /usr/local/bin
          echo "PATH=/usr/local/bin:$PATH" >> $GITHUB_ENV  ## Add Task CLI to PATH
          task --version

      ## Code Quality Checks
      - name: ðŸ’… Lint and Format Check
        run: |
          task check_code_quality

      ## Run Unit Tests
      - name: ðŸ§ª Unit Tests
        run: |
          export PYTHONPATH=src:$PYTHONPATH
          uv run pytest tests/

      ## Test Coverage Report
      - name: ðŸ“Š Test Coverage
        run: |
          uv run pytest --cov=src/runbooks --cov-report=xml tests/

      ## Upload Coverage Report
      - name: ðŸ“ˆ Upload Coverage to Codecov
        uses: codecov/codecov-action@v4
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          file: ./coverage.xml
